version: '3.8'
services:
  console:
    build: .
    command: sleep infinity
    environment:
      BUNDLE_APP_CONFIG: /bundle
      BUNDLE_PATH: /bundle/vendor
      BUNDLE_JOBS: 2
    volumes:
      - .:/app
      - bundle_path:/bundle
volumes:
  bundle_path:
